# Generated by Django 3.2.6 on 2023-05-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='when',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
