# Generated by Django 3.2.6 on 2023-05-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_report_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='medicalstandart',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='medicalstandart',
            name='urled',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
