# Generated by Django 3.2.6 on 2023-05-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20230527_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptionmedicalstandart',
            name='actuality',
            field=models.FloatField(default=0),
        ),
    ]
