# Generated by Django 3.2.6 on 2023-05-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_prescriptionmedicalstandart_actuality'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolprescriptionreal',
            name='show_nmu',
            field=models.BooleanField(default=True),
        ),
    ]
